version: '3'
services:
    mariadb:
        image: 'mariadb:latest'
        ports:
            - 3310:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: askc
            MYSQL_USER: askc
            MYSQL_PASSWORD: askc
        volumes:
            - mysqldata:/var/lib/mysql
volumes:
    mysqldata:
        driver: local
