-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 11:43:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema askc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema askc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `askc` ;
USE `askc` ;

-- -----------------------------------------------------
-- Table `Competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Competition` ;

CREATE TABLE IF NOT EXISTS `Competition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `choosen_formula_id` INT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `place` VARCHAR(255) NULL DEFAULT NULL,
  `owner` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(10) NOT NULL,
  `locked` TINYINT UNSIGNED NULL DEFAULT 0,
  `locked_fighter_list` TINYINT UNSIGNED NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `choosen_formula_id_idx` (`choosen_formula_id` ASC),
  CONSTRAINT `choosen_formula_id`
    FOREIGN KEY (`choosen_formula_id`)
    REFERENCES `Formula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CompetitionFighter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CompetitionFighter` ;

CREATE TABLE IF NOT EXISTS `CompetitionFighter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `competition_id` INT UNSIGNED NOT NULL,
  `license` VARCHAR(16) NOT NULL,
  `grade` VARCHAR(15) NULL DEFAULT NULL,
  `club` VARCHAR(255) NULL DEFAULT NULL,
  `team` VARCHAR(60) NULL DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  `is_present` TINYINT UNSIGNED NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  INDEX `Competition_id_idx` (`competition_id` ASC),
  UNIQUE INDEX `license_UNIQUE` (`license` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `competition_fighter_id_competition`
    FOREIGN KEY (`competition_id`)
    REFERENCES `Competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CompetitionFormula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CompetitionFormula` ;

CREATE TABLE IF NOT EXISTS `CompetitionFormula` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `competition_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCompetitionFormula_UNIQUE` (`id` ASC),
  INDEX `idCompetition_idx` (`competition_id` ASC),
  CONSTRAINT `competition_formula_id_competition`
    FOREIGN KEY (`competition_id`)
    REFERENCES `Competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Formula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Formula` ;

CREATE TABLE IF NOT EXISTS `Formula` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `component_list` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meta` ;

CREATE TABLE IF NOT EXISTS `Meta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metaable_id` INT UNSIGNED NOT NULL,
  `metaable` VARCHAR(45) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idMetaable_idx` (`metaable_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
